apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: infra
  name: redis-pv-claim
  #  annotations:
  #    volume.beta.kubernetes.io/storage-provisioner: nfs-nfs

spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra
spec:
  type: NodePort
  ports:
    - port: 6379     # 容器端口
      nodePort: 30379 # 对外暴露端口
  selector:
    prod: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: infra
spec:
  selector:
    matchLabels:
      prod: redis
  replicas: 1
  template:
    metadata:
      labels:
        prod: redis
    spec:
      containers:
        - name: prod-redis
          ports:
            - containerPort: 6379
          image: redis
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "redis-cli config set requirepass 123456" ]

          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /data/testdata/redis/
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-pv-claim
